services:
  webapp:
    image: maeve2003/webapp:latest
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_URL=mysql://root:uwk3Vcig@database:3306/docker
    volumes:
      - ./database:/app/database
    depends_on:
      - database

  database:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_ROOT_PASSWORD=uwk3Vcig
    volumes:
      - docker_area:/var/lib/mysql

  tests:
    image: maeve2003/webapp:latest
    depends_on:
      - webapp  
    environment:
      - API_URL=http://webapp:3000  
    command: yarn test  

volumes:
  docker_area:
