---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint
        env:
          ESLINT_USE_FLAT_CONFIG: false

      - name: Build Docker image
        uses: philips-software/docker-ci-scripts@v4.5.0
        with:
          dockerfile: ./Dockerfile
          tags: maeve2003/webapp:latest

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Push Docker image to Docker Hub
      #   run: docker push maeve2003/webapp:latest